esphome:
  name: living_room_nodemcu_temphum_sensor
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: "ssid"
  password: "password"
  manual_ip:
    # Set this to the IP of the ESP
    static_ip: 192.168.2.20
    # Set this to the IP address of the router. Often ends with .1
    gateway: 192.168.2.1
    # The subnet of the network. 255.255.255.0 works for most home networks.
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Nodemcu1 Fallback Hotspot"
    password: "2EOmKxU4txdN"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: "mypass"

ota:
  password: "mypass"

sensor:
  - platform: dht
    pin: D6
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
    update_interval: 30s
    model: DHT11